name: action-git-diff-suggestions
description: This GitHub Action will take the current git changes and apply them as GitHub code review suggestions
author: Sentry
branding:
  icon: book-open
  color: purple
inputs:
  github-token:
    description: github token
    default: ${{ github.token }}
  message:
    description: The message to prepend the review suggestion
  pull_request_number:
    description: optional pull_request_number if the github context is not pull_request
    required: false
    #GHA requires a default arg
    default: ''
runs:
  using: node12
  main: dist/index.js
